### ISSUE TITLE
申请适配神舟租车

### ISSUE THREAD

**Issue by nullptr-leo** [pzcn/MIUI-Adapted-Icons-Complement-Project#10]
![Screenshot_2021-03-13-11-01-14-486_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/2814394/111016940-82350c80-83eb-11eb-9f86-239efa7cd2a1.jpg)![Screenshot_2021-03-13-11-01-18-583_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/2814394/111016942-86612a00-83eb-11eb-8817-29e43f997279.jpg)

**Comment by pzcn** [comment]
https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/2247b120cdb81456e3f822ed604f18dd45f44fa8
