### ISSUE TITLE
申请适配 贴吧极速版和游民星空

### ISSUE THREAD

**Issue by Sev73n** [pzcn/MIUI-Adapted-Icons-Complement-Project#12]
![b497b0a36c6fa36927f2a0539fd93cb](https://user-images.githubusercontent.com/16495885/113592411-ae991d00-9667-11eb-8560-be36508b9507.jpg)
![6b7ff601216ae00e4d052fc997794f0](https://user-images.githubusercontent.com/16495885/113592419-b062e080-9667-11eb-98ba-708869b164d7.jpg)

**Comment by pzcn** [comment]
https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/50df256db0d07a5c79ef688e4c82f107e5fcebc8
