### ISSUE TITLE
建议在使用前必读页上加上主题版本信息。

### ISSUE THREAD

**Issue by lukemin** [pzcn/MIUI-Adapted-Icons-Complement-Project#13]
建议在使用前必读页上加上主题版本信息。

**Comment by pzcn** [comment]
目前不存在一个有意义的版本号，取了一个发布的时间戳。后续有时间考虑加上

**Comment by lukemin** [comment]
> 目前不存在一个有意义的版本号，取了一个发布的时间戳。后续有时间考虑加上

加上发布的时间戳也可以啊。
