### ISSUE TITLE
申请适配Microsoft Remote Desktop

### ISSUE THREAD

**Issue by bluskai** [pzcn/MIUI-Adapted-Icons-Complement-Project#8]
现在图标显示有白边，如图
![捕获](https://user-images.githubusercontent.com/37144222/109575621-2639d080-7b2d-11eb-97c5-deb2621137fc.PNG)
应用信息如下：
应用名称：Microsoft Remote Desktop
应用包名：com.microsoft.rdc.android
![Screenshot_2021-03-02-07-50-31-867_com miui securitycenter](https://user-images.githubusercontent.com/37144222/109575677-479abc80-7b2d-11eb-95f0-3f75fddcffb3.jpg)

**Comment by pzcn** [comment]
已添加，同时可以尝试新版MRD https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx
