### ISSUE TITLE
申请适配京东到家

### ISSUE THREAD

**Issue by nullptr-leo** [pzcn/MIUI-Adapted-Icons-Complement-Project#9]
![Screenshot_2021-03-13-10-58-13-849_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/2814394/111016846-12bf1d00-83eb-11eb-928b-581694df6175.jpg)![Screenshot_2021-03-13-10-58-17-808_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/2814394/111016852-19e62b00-83eb-11eb-8ba6-0174da504d20.jpg)![IMG_20210313_105947.jpg](https://user-images.githubusercontent.com/2814394/111016875-3da97100-83eb-11eb-9e83-1cec512bafb9.jpg)

**Comment by pzcn** [comment]
https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/2247b120cdb81456e3f822ed604f18dd45f44fa8 请测试并反馈是否有效

**Comment by nullptr-leo** [comment]
> https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/2247b120cdb81456e3f822ed604f18dd45f44fa8 请测试并反馈是否有效

神州租车可以了，但是感觉logo的主体部分有点偏上，不在正中

京东到家还是不行

**Comment by pzcn** [comment]
> > [2247b12](https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/2247b120cdb81456e3f822ed604f18dd45f44fa8) 请测试并反馈是否有效
> 
> 神州租车可以了，但是感觉logo的主体部分有点偏上，不在正中
> 
> 京东到家还是不行

神州租车已修改，京东到家mtz和模块的修改前、修改后版本在我这边均无问题，无法复现

**Comment by nullptr-leo** [comment]
> > > [2247b12](https://github.com/pzcn/MIUI-Adapted-Icons-Complement-Project/commit/2247b120cdb81456e3f822ed604f18dd45f44fa8) 请测试并反馈是否有效
> > 
> > 神州租车可以了，但是感觉logo的主体部分有点偏上，不在正中
> > 
> > 京东到家还是不行
> 
> 神州租车已修改，京东到家mtz和模块的修改前、修改后版本在我这边均无问题，无法复现

卸载重装就好了 

而且之前截图的图标也不是应用商店最新的，应该是系统的问题
